
# Workflow specific for building the development branches
# Triggers on all branches named dev-***

name: Build-Dev

on:
  push:
    branches: [ dev-* ]

jobs:
  build-dev:

    runs-on: windows-latest
       
    steps:
    - uses: actions/checkout@v2
    - name: Build development branch
      run: .\scripts\Request-DevBuild -Branch ${{ github.ref }}
      shell: pwsh
