# Workflow specific for building the master / main build
# Triggers on all commits and pull-requests on master

name: MainBuild

on:
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
       
    steps:
    - uses: actions/checkout@v2
    #- uses: nelonoel/branch-name@v1
    # Use branch name for whatever purpose    
    - name: Build main
      run: .\scripts\Request-Build -Branch GITHUB_REF
      shell: pwsh
