# Workflow specific for building the master / main build
# Triggers on all commits and pull-requests on master

name: MainBuild

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    - uses: actions/checkout@v2
    
    steps:
    - name: Build main
      run: .\scripts\Request-Build -Branch $github.ref
      shell: pwsh
