name: Main-Check-Commit

on:
  push:
    branches: [ main ]
jobs:
  check-commit:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Create development branch and build
      run: .\scripts\Check-CommitMessage -GithubContext ${{ github.event }}
      shell: pwsh
