# Workflow specific for building the master / main build
# Triggers on all commits on master

name: PullRequest-Main

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
       
    steps:
    - uses: actions/checkout@v2
    - name: Build main
      run: .\scripts\Request-PullRequest ${{ github.ref }}
      shell: pwsh
